### ISSUE TITLE
Categories need localising

### ISSUE THREAD

**Issue by jamieadkins95** [GwentCommunityDevelopers/gwent-data#1]
At the moment, categories are hard coded in English. Ideally we should have these localised like other pieces of card data.

**Comment by Zolmeister** [comment]
Given they're token enums, it's probably better to produce a translation mapping document separately

**Comment by Tri125** [comment]
If they aren't localized somewhere in some xml or if it's proven too much of an hassle to find it, the mapping is probably for the best. I would prefer to avoid hardcoded mapping, the day the game add a new category or remove old one, we have to go back to the script and change it, we would have to keep track of the game changes more closely. Maybe make sure that the script alert us if it detects a case like that, this can't be allowed to go silently.

My personal take is I'd rather have no localization than risk having a localization that is bad which is why I haven't personally translated categories, rarities, and the likes for my api. My mother tongue is french so I can translate to that language or put my seal of approval on a french translation.

**Comment by jamieadkins95** [comment]
I've just had a poke around the Gwent files to find this localisation.

They are in the format:
`"interface";"card_category_no_decoyable";"Stubborn"`
`"interface";"card_category_necrophage";"Necrophage"`

They are stored in a csv file called 
`interface_en-us.csv`

Which can be found in 
`/Gwent/GWENT_Data/StreamingAssets/AssetBundles/Localization/en-us/text.en-us`

This is a Unity AssetBundle that has to be unpacked using something like [UABE](https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor).

Note that by default, only the localisation you use in the game is downloaded. You have to launch the game in all of the localisations to get all of the folders for this.

**Comment by jamieadkins95** [comment]
It is a lot of effort to go and obtain these files for every patch. My initial suggestion would be to create a mapping for these once, based on the localisations files described above, and then apply them to every patch.

It is unlikely that these will change in the future, since they are descriptions for core mechanics that I doubt CDPR would like to keep changing. If there is a change, I think it would be fairly obvious and won't go unnoticed.

This method is weak to new cards being released with new category tags that are not used elsewhere. Thos are not as easy to spot.

**Comment by jamieadkins95** [comment]
Categories are now localised and included in the categories.json output.
